name: Synk Forks and Build

# Controls when the workflow will run
on:
  schedule:
    - cron:  '00 21 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # # Tmate ##
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    
    - name: Synk Forks
      run: |
        echo ${{ secrets.SYNK_TOKEN }} | gh auth login --with-token
        gh repo sync ${{ github.repository }}

